server:
  port: 8082

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: qxglServer
        uri: http://192.168.3.210:8887
        order: 0
        predicates:
        - Path=/qxglServer/**
        filters:
        - StripPrefix=1
      - id: qyglServer
        uri: http://192.168.3.210:9090
        order: 1
        predicates:
        - Path=/qyglServer/**
        filters:
        - StripPrefix=1
      - id: zhjg
        uri: http://127.0.0.1:8889
        order: 2
        predicates:
        - Path=/zhjg/**
        filters:
        - StripPrefix=1
      - id: zcbg
        uri: http://127.0.0.1:8080
        order: 3
        predicates:
        - Path=/zcbg/**
        filters:
        - StripPrefix=1
      - id: zssb
        uri: http://127.0.0.1:8888
        order: 4
        predicates:
        - Path=/zssb/**
        filters:
        - StripPrefix=1
  redis:
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    host: 192.168.3.206
    database: 3
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 300
        # 连接池中的最小空闲连接
        max-idle: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接超时时间（毫秒）
        timeout: 5000
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8088/eureka/



filter:
  ignore: /qxgl/getToken

feign:
  httpclient:
    enabled: true


#logging:
#  level:
#    org.springframework.cloud.gateway: info

logging:
  config: classpath:log4j2.xml


